#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20200617_LinqToSql_Giris
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KuzeyYeli")]
	public partial class NorthwindDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUrunler(Urunler instance);
    partial void UpdateUrunler(Urunler instance);
    partial void DeleteUrunler(Urunler instance);
    partial void InsertKategoriler(Kategoriler instance);
    partial void UpdateKategoriler(Kategoriler instance);
    partial void DeleteKategoriler(Kategoriler instance);
    partial void InsertSatislar(Satislar instance);
    partial void UpdateSatislar(Satislar instance);
    partial void DeleteSatislar(Satislar instance);
    partial void InsertTedarikciler(Tedarikciler instance);
    partial void UpdateTedarikciler(Tedarikciler instance);
    partial void DeleteTedarikciler(Tedarikciler instance);
    #endregion
		
		public NorthwindDataContext() : 
				base(global::_20200617_LinqToSql_Giris.Properties.Settings.Default.KuzeyYeliConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Urunler> Urunlers
		{
			get
			{
				return this.GetTable<Urunler>();
			}
		}
		
		public System.Data.Linq.Table<Kategoriler> Kategorilers
		{
			get
			{
				return this.GetTable<Kategoriler>();
			}
		}
		
		public System.Data.Linq.Table<Satislar> Satislars
		{
			get
			{
				return this.GetTable<Satislar>();
			}
		}
		
		public System.Data.Linq.Table<Tedarikciler> Tedarikcilers
		{
			get
			{
				return this.GetTable<Tedarikciler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urunler")]
	public partial class Urunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UrunID;
		
		private string _UrunAdi;
		
		private System.Nullable<int> _TedarikciID;
		
		private System.Nullable<int> _KategoriID;
		
		private string _BirimdekiMiktar;
		
		private System.Nullable<decimal> _Fiyat;
		
		private System.Nullable<short> _Stok;
		
		private System.Nullable<short> _YeniSatis;
		
		private System.Nullable<short> _EnAzYenidenSatisMikatari;
		
		private bool _Sonlandi;
		
		private EntityRef<Kategoriler> _Kategoriler;
		
		private EntityRef<Tedarikciler> _Tedarikciler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnUrunAdiChanging(string value);
    partial void OnUrunAdiChanged();
    partial void OnTedarikciIDChanging(System.Nullable<int> value);
    partial void OnTedarikciIDChanged();
    partial void OnKategoriIDChanging(System.Nullable<int> value);
    partial void OnKategoriIDChanged();
    partial void OnBirimdekiMiktarChanging(string value);
    partial void OnBirimdekiMiktarChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    partial void OnStokChanging(System.Nullable<short> value);
    partial void OnStokChanged();
    partial void OnYeniSatisChanging(System.Nullable<short> value);
    partial void OnYeniSatisChanged();
    partial void OnEnAzYenidenSatisMikatariChanging(System.Nullable<short> value);
    partial void OnEnAzYenidenSatisMikatariChanged();
    partial void OnSonlandiChanging(bool value);
    partial void OnSonlandiChanged();
    #endregion
		
		public Urunler()
		{
			this._Kategoriler = default(EntityRef<Kategoriler>);
			this._Tedarikciler = default(EntityRef<Tedarikciler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this.OnUrunAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunAdi = value;
					this.SendPropertyChanged("UrunAdi");
					this.OnUrunAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TedarikciID", DbType="Int")]
		public System.Nullable<int> TedarikciID
		{
			get
			{
				return this._TedarikciID;
			}
			set
			{
				if ((this._TedarikciID != value))
				{
					if (this._Tedarikciler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTedarikciIDChanging(value);
					this.SendPropertyChanging();
					this._TedarikciID = value;
					this.SendPropertyChanged("TedarikciID");
					this.OnTedarikciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", DbType="Int")]
		public System.Nullable<int> KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					if (this._Kategoriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirimdekiMiktar", DbType="NVarChar(20)")]
		public string BirimdekiMiktar
		{
			get
			{
				return this._BirimdekiMiktar;
			}
			set
			{
				if ((this._BirimdekiMiktar != value))
				{
					this.OnBirimdekiMiktarChanging(value);
					this.SendPropertyChanging();
					this._BirimdekiMiktar = value;
					this.SendPropertyChanged("BirimdekiMiktar");
					this.OnBirimdekiMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Money")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok", DbType="SmallInt")]
		public System.Nullable<short> Stok
		{
			get
			{
				return this._Stok;
			}
			set
			{
				if ((this._Stok != value))
				{
					this.OnStokChanging(value);
					this.SendPropertyChanging();
					this._Stok = value;
					this.SendPropertyChanged("Stok");
					this.OnStokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeniSatis", DbType="SmallInt")]
		public System.Nullable<short> YeniSatis
		{
			get
			{
				return this._YeniSatis;
			}
			set
			{
				if ((this._YeniSatis != value))
				{
					this.OnYeniSatisChanging(value);
					this.SendPropertyChanging();
					this._YeniSatis = value;
					this.SendPropertyChanged("YeniSatis");
					this.OnYeniSatisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnAzYenidenSatisMikatari", DbType="SmallInt")]
		public System.Nullable<short> EnAzYenidenSatisMikatari
		{
			get
			{
				return this._EnAzYenidenSatisMikatari;
			}
			set
			{
				if ((this._EnAzYenidenSatisMikatari != value))
				{
					this.OnEnAzYenidenSatisMikatariChanging(value);
					this.SendPropertyChanging();
					this._EnAzYenidenSatisMikatari = value;
					this.SendPropertyChanged("EnAzYenidenSatisMikatari");
					this.OnEnAzYenidenSatisMikatariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonlandi", DbType="Bit NOT NULL")]
		public bool Sonlandi
		{
			get
			{
				return this._Sonlandi;
			}
			set
			{
				if ((this._Sonlandi != value))
				{
					this.OnSonlandiChanging(value);
					this.SendPropertyChanging();
					this._Sonlandi = value;
					this.SendPropertyChanged("Sonlandi");
					this.OnSonlandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoriler_Urunler", Storage="_Kategoriler", ThisKey="KategoriID", OtherKey="KategoriID", IsForeignKey=true)]
		public Kategoriler Kategoriler
		{
			get
			{
				return this._Kategoriler.Entity;
			}
			set
			{
				Kategoriler previousValue = this._Kategoriler.Entity;
				if (((previousValue != value) 
							|| (this._Kategoriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategoriler.Entity = null;
						previousValue.Urunlers.Remove(this);
					}
					this._Kategoriler.Entity = value;
					if ((value != null))
					{
						value.Urunlers.Add(this);
						this._KategoriID = value.KategoriID;
					}
					else
					{
						this._KategoriID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategoriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tedarikciler_Urunler", Storage="_Tedarikciler", ThisKey="TedarikciID", OtherKey="TedarikciID", IsForeignKey=true)]
		public Tedarikciler Tedarikciler
		{
			get
			{
				return this._Tedarikciler.Entity;
			}
			set
			{
				Tedarikciler previousValue = this._Tedarikciler.Entity;
				if (((previousValue != value) 
							|| (this._Tedarikciler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tedarikciler.Entity = null;
						previousValue.Urunlers.Remove(this);
					}
					this._Tedarikciler.Entity = value;
					if ((value != null))
					{
						value.Urunlers.Add(this);
						this._TedarikciID = value.TedarikciID;
					}
					else
					{
						this._TedarikciID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tedarikciler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategoriler")]
	public partial class Kategoriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KategoriID;
		
		private string _KategoriAdi;
		
		private string _Tanimi;
		
		private System.Data.Linq.Binary _Resim;
		
		private EntitySet<Urunler> _Urunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategoriIDChanging(int value);
    partial void OnKategoriIDChanged();
    partial void OnKategoriAdiChanging(string value);
    partial void OnKategoriAdiChanged();
    partial void OnTanimiChanging(string value);
    partial void OnTanimiChanged();
    partial void OnResimChanging(System.Data.Linq.Binary value);
    partial void OnResimChanged();
    #endregion
		
		public Kategoriler()
		{
			this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KategoriAdi
		{
			get
			{
				return this._KategoriAdi;
			}
			set
			{
				if ((this._KategoriAdi != value))
				{
					this.OnKategoriAdiChanging(value);
					this.SendPropertyChanging();
					this._KategoriAdi = value;
					this.SendPropertyChanged("KategoriAdi");
					this.OnKategoriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanimi", DbType="NVarChar(500)")]
		public string Tanimi
		{
			get
			{
				return this._Tanimi;
			}
			set
			{
				if ((this._Tanimi != value))
				{
					this.OnTanimiChanging(value);
					this.SendPropertyChanging();
					this._Tanimi = value;
					this.SendPropertyChanged("Tanimi");
					this.OnTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoriler_Urunler", Storage="_Urunlers", ThisKey="KategoriID", OtherKey="KategoriID")]
		public EntitySet<Urunler> Urunlers
		{
			get
			{
				return this._Urunlers;
			}
			set
			{
				this._Urunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Kategoriler = this;
		}
		
		private void detach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Kategoriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Satislar")]
	public partial class Satislar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisID;
		
		private string _MusteriID;
		
		private System.Nullable<int> _PersonelID;
		
		private System.Nullable<System.DateTime> _SatisTarihi;
		
		private System.Nullable<System.DateTime> _OdemeTarihi;
		
		private System.Nullable<System.DateTime> _SevkTarihi;
		
		private System.Nullable<int> _ShipVia;
		
		private System.Nullable<decimal> _NakliyeUcreti;
		
		private string _SevkAdi;
		
		private string _SevkAdresi;
		
		private string _SevkSehri;
		
		private string _SevkBolgesi;
		
		private string _SevkPostaKodu;
		
		private string _SevkUlkesi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisIDChanging(int value);
    partial void OnSatisIDChanged();
    partial void OnMusteriIDChanging(string value);
    partial void OnMusteriIDChanged();
    partial void OnPersonelIDChanging(System.Nullable<int> value);
    partial void OnPersonelIDChanged();
    partial void OnSatisTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSatisTarihiChanged();
    partial void OnOdemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOdemeTarihiChanged();
    partial void OnSevkTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSevkTarihiChanged();
    partial void OnShipViaChanging(System.Nullable<int> value);
    partial void OnShipViaChanged();
    partial void OnNakliyeUcretiChanging(System.Nullable<decimal> value);
    partial void OnNakliyeUcretiChanged();
    partial void OnSevkAdiChanging(string value);
    partial void OnSevkAdiChanged();
    partial void OnSevkAdresiChanging(string value);
    partial void OnSevkAdresiChanged();
    partial void OnSevkSehriChanging(string value);
    partial void OnSevkSehriChanged();
    partial void OnSevkBolgesiChanging(string value);
    partial void OnSevkBolgesiChanged();
    partial void OnSevkPostaKoduChanging(string value);
    partial void OnSevkPostaKoduChanged();
    partial void OnSevkUlkesiChanging(string value);
    partial void OnSevkUlkesiChanged();
    #endregion
		
		public Satislar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatisID
		{
			get
			{
				return this._SatisID;
			}
			set
			{
				if ((this._SatisID != value))
				{
					this.OnSatisIDChanging(value);
					this.SendPropertyChanging();
					this._SatisID = value;
					this.SendPropertyChanged("SatisID");
					this.OnSatisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="NChar(5)")]
		public string MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int")]
		public System.Nullable<int> PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SatisTarihi
		{
			get
			{
				return this._SatisTarihi;
			}
			set
			{
				if ((this._SatisTarihi != value))
				{
					this.OnSatisTarihiChanging(value);
					this.SendPropertyChanging();
					this._SatisTarihi = value;
					this.SendPropertyChanged("SatisTarihi");
					this.OnSatisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> OdemeTarihi
		{
			get
			{
				return this._OdemeTarihi;
			}
			set
			{
				if ((this._OdemeTarihi != value))
				{
					this.OnOdemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._OdemeTarihi = value;
					this.SendPropertyChanged("OdemeTarihi");
					this.OnOdemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SevkTarihi
		{
			get
			{
				return this._SevkTarihi;
			}
			set
			{
				if ((this._SevkTarihi != value))
				{
					this.OnSevkTarihiChanging(value);
					this.SendPropertyChanging();
					this._SevkTarihi = value;
					this.SendPropertyChanged("SevkTarihi");
					this.OnSevkTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipVia", DbType="Int")]
		public System.Nullable<int> ShipVia
		{
			get
			{
				return this._ShipVia;
			}
			set
			{
				if ((this._ShipVia != value))
				{
					this.OnShipViaChanging(value);
					this.SendPropertyChanging();
					this._ShipVia = value;
					this.SendPropertyChanged("ShipVia");
					this.OnShipViaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NakliyeUcreti", DbType="Money")]
		public System.Nullable<decimal> NakliyeUcreti
		{
			get
			{
				return this._NakliyeUcreti;
			}
			set
			{
				if ((this._NakliyeUcreti != value))
				{
					this.OnNakliyeUcretiChanging(value);
					this.SendPropertyChanging();
					this._NakliyeUcreti = value;
					this.SendPropertyChanged("NakliyeUcreti");
					this.OnNakliyeUcretiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkAdi", DbType="NVarChar(40)")]
		public string SevkAdi
		{
			get
			{
				return this._SevkAdi;
			}
			set
			{
				if ((this._SevkAdi != value))
				{
					this.OnSevkAdiChanging(value);
					this.SendPropertyChanging();
					this._SevkAdi = value;
					this.SendPropertyChanged("SevkAdi");
					this.OnSevkAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkAdresi", DbType="NVarChar(60)")]
		public string SevkAdresi
		{
			get
			{
				return this._SevkAdresi;
			}
			set
			{
				if ((this._SevkAdresi != value))
				{
					this.OnSevkAdresiChanging(value);
					this.SendPropertyChanging();
					this._SevkAdresi = value;
					this.SendPropertyChanged("SevkAdresi");
					this.OnSevkAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkSehri", DbType="NVarChar(15)")]
		public string SevkSehri
		{
			get
			{
				return this._SevkSehri;
			}
			set
			{
				if ((this._SevkSehri != value))
				{
					this.OnSevkSehriChanging(value);
					this.SendPropertyChanging();
					this._SevkSehri = value;
					this.SendPropertyChanged("SevkSehri");
					this.OnSevkSehriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkBolgesi", DbType="NVarChar(15)")]
		public string SevkBolgesi
		{
			get
			{
				return this._SevkBolgesi;
			}
			set
			{
				if ((this._SevkBolgesi != value))
				{
					this.OnSevkBolgesiChanging(value);
					this.SendPropertyChanging();
					this._SevkBolgesi = value;
					this.SendPropertyChanged("SevkBolgesi");
					this.OnSevkBolgesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkPostaKodu", DbType="NVarChar(10)")]
		public string SevkPostaKodu
		{
			get
			{
				return this._SevkPostaKodu;
			}
			set
			{
				if ((this._SevkPostaKodu != value))
				{
					this.OnSevkPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._SevkPostaKodu = value;
					this.SendPropertyChanged("SevkPostaKodu");
					this.OnSevkPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkUlkesi", DbType="NVarChar(15)")]
		public string SevkUlkesi
		{
			get
			{
				return this._SevkUlkesi;
			}
			set
			{
				if ((this._SevkUlkesi != value))
				{
					this.OnSevkUlkesiChanging(value);
					this.SendPropertyChanging();
					this._SevkUlkesi = value;
					this.SendPropertyChanged("SevkUlkesi");
					this.OnSevkUlkesiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tedarikciler")]
	public partial class Tedarikciler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TedarikciID;
		
		private string _SirketAdi;
		
		private string _MusteriAdi;
		
		private string _MusteriUnvani;
		
		private string _Adres;
		
		private string _Sehir;
		
		private string _Bolge;
		
		private string _PostaKodu;
		
		private string _Ulke;
		
		private string _Telefon;
		
		private string _Faks;
		
		private string _WebSayfasi;
		
		private EntitySet<Urunler> _Urunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTedarikciIDChanging(int value);
    partial void OnTedarikciIDChanged();
    partial void OnSirketAdiChanging(string value);
    partial void OnSirketAdiChanged();
    partial void OnMusteriAdiChanging(string value);
    partial void OnMusteriAdiChanged();
    partial void OnMusteriUnvaniChanging(string value);
    partial void OnMusteriUnvaniChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnBolgeChanging(string value);
    partial void OnBolgeChanged();
    partial void OnPostaKoduChanging(string value);
    partial void OnPostaKoduChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnFaksChanging(string value);
    partial void OnFaksChanged();
    partial void OnWebSayfasiChanging(string value);
    partial void OnWebSayfasiChanged();
    #endregion
		
		public Tedarikciler()
		{
			this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TedarikciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TedarikciID
		{
			get
			{
				return this._TedarikciID;
			}
			set
			{
				if ((this._TedarikciID != value))
				{
					this.OnTedarikciIDChanging(value);
					this.SendPropertyChanging();
					this._TedarikciID = value;
					this.SendPropertyChanged("TedarikciID");
					this.OnTedarikciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SirketAdi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string SirketAdi
		{
			get
			{
				return this._SirketAdi;
			}
			set
			{
				if ((this._SirketAdi != value))
				{
					this.OnSirketAdiChanging(value);
					this.SendPropertyChanging();
					this._SirketAdi = value;
					this.SendPropertyChanged("SirketAdi");
					this.OnSirketAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="NVarChar(30)")]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this.OnMusteriAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriAdi = value;
					this.SendPropertyChanged("MusteriAdi");
					this.OnMusteriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriUnvani", DbType="NVarChar(30)")]
		public string MusteriUnvani
		{
			get
			{
				return this._MusteriUnvani;
			}
			set
			{
				if ((this._MusteriUnvani != value))
				{
					this.OnMusteriUnvaniChanging(value);
					this.SendPropertyChanging();
					this._MusteriUnvani = value;
					this.SendPropertyChanged("MusteriUnvani");
					this.OnMusteriUnvaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(60)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(15)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bolge", DbType="NVarChar(15)")]
		public string Bolge
		{
			get
			{
				return this._Bolge;
			}
			set
			{
				if ((this._Bolge != value))
				{
					this.OnBolgeChanging(value);
					this.SendPropertyChanging();
					this._Bolge = value;
					this.SendPropertyChanged("Bolge");
					this.OnBolgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostaKodu", DbType="NVarChar(10)")]
		public string PostaKodu
		{
			get
			{
				return this._PostaKodu;
			}
			set
			{
				if ((this._PostaKodu != value))
				{
					this.OnPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._PostaKodu = value;
					this.SendPropertyChanged("PostaKodu");
					this.OnPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(15)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(24)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faks", DbType="NVarChar(24)")]
		public string Faks
		{
			get
			{
				return this._Faks;
			}
			set
			{
				if ((this._Faks != value))
				{
					this.OnFaksChanging(value);
					this.SendPropertyChanging();
					this._Faks = value;
					this.SendPropertyChanged("Faks");
					this.OnFaksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSayfasi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string WebSayfasi
		{
			get
			{
				return this._WebSayfasi;
			}
			set
			{
				if ((this._WebSayfasi != value))
				{
					this.OnWebSayfasiChanging(value);
					this.SendPropertyChanging();
					this._WebSayfasi = value;
					this.SendPropertyChanged("WebSayfasi");
					this.OnWebSayfasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tedarikciler_Urunler", Storage="_Urunlers", ThisKey="TedarikciID", OtherKey="TedarikciID")]
		public EntitySet<Urunler> Urunlers
		{
			get
			{
				return this._Urunlers;
			}
			set
			{
				this._Urunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Tedarikciler = this;
		}
		
		private void detach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Tedarikciler = null;
		}
	}
}
#pragma warning restore 1591
